feat: update workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,84 +8,128 @@ on:
         type: environment
         required: true
 jobs:
-  deploy:
+  perpare-deployment:
     environment: ${{ inputs.environment }}
-    name: Deploy Snap and UI
-    runs-on: ubuntu-20.04
+    permissions:
+      contents: write
+    runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
+      - uses: actions/checkout@v3
         with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: eu-central-1
-
-      - name: Use Node.js 16.x
-        uses: actions/setup-node@v2
+          ref: ${{ github.sha }}
+      - name: Setup Node.js
+        uses: actions/setup-node@v3
         with:
           node-version: 20.x
-          registry-url: 'https://registry.npmjs.org'
-      - name: Get Yarn cache directory
-        run: echo "::set-output name=YARN_CACHE_DIR::$(yarn cache dir)"
-        id: yarn-cache-dir
-      - name: Get Yarn version
-        run: echo "::set-output name=YARN_VERSION::$(yarn --version)"
-        id: yarn-version
-      - name: Cache yarn dependencies
-        uses: actions/cache@v2
+      - name: Prepare parameters 
+        id: prepare_parameters
+        run: |
+          BASE=$(node -p "require('./packages/starknet-snap/package.json').version")
+          HASH=$(git rev-parse --short HEAD)
+          DATE=$(date +%Y%m%d)
+          ENV=${{ inputs.environment }}
+          if [[ $ENV == "dev" ]]; then
+            {
+              echo "VERSION=${BASE}-dev-${HASH}-${DATE}"
+              echo "TAG=dev"
+              echo "ENV=dev"
+            } >> "$GITHUB_OUTPUT"
+          elif [[ $ENV  == "staging" ]]; then
+            {
+              echo "VERSION=${BASE}-staging"
+              echo "TAG=staging"
+              echo "ENV=staging"
+            } >> "$GITHUB_OUTPUT"
+          elif [[ $ENV  == "production" ]]; then
+            {
+              echo "VERSION=${BASE}"
+              echo "TAG=latest"
+              echo "ENV=prod"
+            } >> "$GITHUB_OUTPUT"
+          else
+            echo "Invalid environment"
+            exit 1
+          fi
+    outputs:
+      VERSION: ${{ steps.prepare_parameters.outputs.VERSION }}
+      TAG: ${{ steps.prepare_parameters.outputs.TAG }}
+      ENV: ${{ steps.prepare_parameters.outputs.ENV }}
+      AWS_CLOUDFRONT_DISTRIBUTIONS_ID: ${{ vars.AWS_CLOUDFRONT_DISTRIBUTIONS_ID }}
+      AWS_S3_URL: ${{ vars.AWS_S3_URL }}
+
+  install-build:
+    needs: 
+      - perpare-deployment
+    permissions:
+      contents: write
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
         with:
-          path: ${{ steps.yarn-cache-dir.outputs.YARN_CACHE_DIR }}
-          key: yarn-cache-${{ runner.os }}-${{ steps.yarn-version.outputs.YARN_VERSION }}-${{ hashFiles('yarn.lock') }}
-      - run: yarn install --no-immutable
-      - run: yarn setup
-      - run: yarn clean
-
-      - name: Staging Deployment
+          ref: ${{ github.sha }}
+      - name: Setup Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version-file: '20.x'
+      - name: Install
         run: |
-          VERSION=$(node -p "require('./packages/starknet-snap/package.json').version")
-          REACT_APP_SNAP_VERSION=${VERSION}-staging yarn workspace wallet-ui build
-          
-          npm --prefix ./packages/starknet-snap version --new-version ${VERSION}-staging --no-git-tag-version
+          yarn install --no-immutable
+      - name: Build Snap
+        run: |
+          PRE_VERSION="$VERSION"
+
+          npm --prefix ./packages/starknet-snap version --new-version "$PRE_VERSION" --no-git-tag-version --allow-same-version
+
           yarn workspace @consensys/starknet-snap build
+
+          BUILD_VERSION=$(node -p "require('./packages/starknet-snap/package.json').version")
           
-          npm publish ./packages/starknet-snap  --tag staging --access public 2>&1 > /dev/null || :
-          aws s3 sync ./packages/wallet-ui/build s3://staging.snaps.consensys.io/starknet
+          if [[ "$PRE_VERSION" != "$BUILD_VERSION" ]]; then
+            echo "Version mismatch"
+            exit 1
+          fi
         env:
-          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
-          SNAP_ENV: staging
+          SNAP_ENV: ${{ needs.perpare-deployment.outputs.ENV }}
+          VERSION: ${{ needs.perpare-deployment.outputs.VERSION }}
           VOYAGER_API_KEY: ${{ secrets.VOYAGER_API_KEY }}
           ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
-        if: inputs.environment == 'staging'
-
-      - name: Production Deployment
+      - name: Build UI
         run: |
-          VERSION=$(node -p "require('./packages/starknet-snap/package.json').version")
-          REACT_APP_SNAP_VERSION=${VERSION} REACT_APP_DEBUG_LEVEL=off yarn workspace wallet-ui build
-
-          npm --prefix ./packages/starknet-snap version --new-version ${VERSION} --no-git-tag-version --allow-same-version
-          yarn workspace @consensys/starknet-snap build
-          
-          npm publish ./packages/starknet-snap --tag latest --access public 2>&1 > /dev/null || :
-          aws s3 sync ./packages/wallet-ui/build s3://snaps.consensys.io/starknet
+          REACT_APP_SNAP_VERSION="$VERSION" yarn workspace wallet-ui build 
         env:
-          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
-          SNAP_ENV: prod
-          VOYAGER_API_KEY: ${{ secrets.VOYAGER_API_KEY }}
-          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
-        if: inputs.environment == 'production'
+          VERSION: ${{ needs.perpare-deployment.outputs.VERSION }}
+      - uses: actions/cache@v3
+        id: restore-build
+        with:
+          path: |
+            ./packages/wallet-ui/build/*
+            ./packages/starknet-snap/dist/bundle.js
+            ./packages/starknet-snap/snap.manifest.json
+            ./node_modules/.yarn-state.yml
+          key: ${{ github.sha }}
 
-      - name: invalid aws cloudfront cache
-        env: 
-          AWS_CLOUDFRONT_DISTRIBUTIONS_ID: ${{ vars.AWS_CLOUDFRONT_DISTRIBUTIONS_ID }}
-        run: |
-          echo "Distribution ID : $AWS_CLOUDFRONT_DISTRIBUTIONS_ID"
-          for process in $(echo $AWS_CLOUDFRONT_DISTRIBUTIONS_ID | sed "s/,/ /g")
-          do
-              echo "Processing Distribution ID : $process"
-              id="$(aws cloudfront create-invalidation --distribution-id $process --paths "/starknet/*" | grep Id | awk -F'"' '{ print $4}')"
-              echo "Waiting for invalidation $id"
-              aws cloudfront wait invalidation-completed --id $id --distribution-id $process
-              echo "Invalidation $id completed"
-          done
+  deploy-snap:
+    needs: 
+      - perpare-deployment
+      - install-build
+    name: Deploy Snap
+    permissions:
+      contents: write
+    uses: ./.github/workflows/publish-release.yml
+    secrets:
+      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+      TAG: ${{ needs.perpare-deployment.outputs.TAG }}
+
+  deploy-dapp:
+    needs: 
+      - perpare-deployment
+      - deploy-snap
+    name: Deploy Dapp
+    permissions:
+      contents: write
+    uses: ./.github/workflows/publish-dapp.yml
+    secrets:
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      AWS_CLOUDFRONT_DISTRIBUTIONS_ID: ${{ needs.perpare-deployment.outputs.AWS_CLOUDFRONT_DISTRIBUTIONS_ID }}
+      AWS_S3_URL: ${{ needs.perpare-deployment.outputs.AWS_S3_URL }}
